version: "3"

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  stonex:
    build:
      context: .
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: stonex_dev
      PGPORT: 5432
      PGHOST: db
    container_name: stonex
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - .:/stonex
    depends_on:
      - db
volumes:
  pgdata:
